### ISSUE TITLE
Run c2sp.org/CCTV/age testkit

### ISSUE THREAD

**Issue by FiloSottile** [Producement/dage#3]
Hello! Thank you for building this!

There is a large set of test vectors at https://c2sp.org/CCTV/age that I recommend any implementation use to test spec conformance. Here are two examples of how they can be used. They are fairly flexible, so you you can for example skip any tests for features you don't implement, if any.

https://github.com/FiloSottile/typage/blob/main/tests/testkit.test.ts

https://github.com/FiloSottile/age/blob/main/testkit_test.go

**Comment by v3rm0n** [comment]
@FiloSottile skipped armored for now, added rest https://github.com/Producement/dage/actions/runs/7755537015/job/21151121048

**Comment by v3rm0n** [comment]
Added armoring support as well, all test vectors are implemented.
